{
 "title": "Ray SageMaker Training Job",
 "description": "Combined Ray cluster and training metrics for SageMaker training jobs. Select a SessionName to filter by training job.",
 "tags": [
  "ray",
  "sagemaker",
  "training"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_node_cpu_utilization{}, SessionName)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(ray_node_cpu_utilization{SessionName=~\"$SessionName\"}, instance)"
    }
   },
   {
    "name": "TrainRunName",
    "query": {
     "query": "label_values(ray_train_worker_group_start_total_time_s{SessionName=~\"$SessionName\"}, ray_train_run_name)"
    }
   },
   {
    "name": "RayNodeType",
    "query": {
     "query": "label_values(ray_node_cpu_utilization{SessionName=~\"$SessionName\"}, RayNodeType)"
    }
   },
   {
    "name": "TrainRunId",
    "query": {
     "query": "label_values(ray_train_controller_state{SessionName=~\"$SessionName\"}, ray_train_run_id)"
    }
   },
   {
    "name": "TrainWorkerWorldRank",
    "query": {
     "query": "label_values(ray_train_report_total_blocked_time_s{SessionName=~\"$SessionName\"}, ray_train_worker_world_rank)"
    }
   },
   {
    "name": "TrainWorkerActorId",
    "query": {
     "query": "label_values(ray_train_report_total_blocked_time_s{SessionName=~\"$SessionName\"}, ray_train_worker_actor_id)"
    }
   },
   {
    "name": "TrainingJobName",
    "query": {
     "query": "label_values(ray_node_cpu_utilization{}, sagemaker_training_job_name)"
    }
   },
   {
    "name": "InstanceType",
    "query": {
     "query": "label_values(ray_node_cpu_utilization{SessionName=~\"$SessionName\"}, instance_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "Note: not impacted by \"Instance\" variable.\n\nA total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization",
   "type": "timeseries",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) / on() (sum(ray_node_gpus_available{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) / on() (sum(ray_node_mem_total{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) / on() (sum(ray_node_gram_available{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) + sum(ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) / on() sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) / on() (sum(ray_node_disk_free{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) + sum(ray_node_disk_usage{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  { "title": "Training Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Controller State",
   "type": "state-timeline",
   "description": "Current state of the train controller.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(ray_train_controller_state{ray_train_run_name=~\"$TrainRunName\", ray_train_run_id=~\"$TrainRunId\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (ray_train_run_name, ray_train_controller_state)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Controller State: {{ray_train_controller_state}}"
    }
   ]
  },
  {
   "title": "Controller Operation Time",
   "type": "timeseries",
   "description": "Time taken by the controller for worker group operations.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "sum(ray_train_worker_group_start_total_time_s{ray_train_run_name=~\"$TrainRunName\", ray_train_run_id=~\"$TrainRunId\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (ray_train_run_name)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Worker Group Start Time"
    },
    {
     "expr": "sum(ray_train_worker_group_shutdown_total_time_s{ray_train_run_name=~\"$TrainRunName\", ray_train_run_id=~\"$TrainRunId\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (ray_train_run_name)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, Worker Group Shutdown Time"
    }
   ]
  },
  {
   "title": "Checkpoint Report Time",
   "type": "timeseries",
   "description": "Time taken to report a checkpoint to storage.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "sum(ray_train_report_total_blocked_time_s{ray_train_run_name=~\"$TrainRunName\", ray_train_run_id=~\"$TrainRunId\", ray_train_worker_world_rank=~\"$TrainWorkerWorldRank\", ray_train_worker_actor_id=~\"$TrainWorkerActorId\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (ray_train_run_name, ray_train_worker_world_rank, ray_train_worker_actor_id)",
     "legendFormat": "Run Name: {{ray_train_run_name}}, World Rank: {{ray_train_worker_world_rank}}"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Node GPU Usage",
   "type": "timeseries",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"} / 100) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "GPU Usage: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Usage %",
   "type": "timeseries",
   "description": "Node's physical (hardware) GPU usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_node_gpus_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "GPU Usage: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage (GRAM)",
   "type": "timeseries",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"} * 1024 * 1024) by (instance, RayNodeType, GpuIndex, GpuDeviceName)",
     "legendFormat": "Used GRAM: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) + sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Memory Usage (GRAM) %",
   "type": "timeseries",
   "description": "The percentage of physical (hardware) GPU memory usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName) * 100 / (sum(ray_node_gram_available{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName) + sum(ray_node_gram_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType, GpuIndex, GpuDeviceName))",
     "legendFormat": "Used GRAM: {{instance}} ({{RayNodeType}}), gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "description": "The physical (hardware) CPU usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"} * ray_node_cpu_count{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"} / 100) by (instance, RayNodeType)",
     "legendFormat": "CPU Usage: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_cpu_count{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node CPU Usage %",
   "type": "timeseries",
   "description": "The percentage of physical (hardware) CPU usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "CPU Usage: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Memory Usage (heap + object store)",
   "type": "timeseries",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Memory Used: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_mem_total{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory Usage % (heap + object store)",
   "type": "timeseries",
   "description": "The percentage of physical (hardware) memory usage for each node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Memory Used: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  { "title": "Network & Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Node Network",
   "type": "timeseries",
   "description": "Network speed per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Recv: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_network_send_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Send: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Disk IO Speed",
   "type": "timeseries",
   "description": "Disk IO per node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(ray_node_disk_io_write_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Write: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_disk_io_read_speed{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Read: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "timeseries",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType)",
     "legendFormat": "Disk Used: {{instance}} ({{RayNodeType}})"
    },
    {
     "expr": "sum(ray_node_disk_free{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) + sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk Usage %",
   "type": "timeseries",
   "description": "Node's physical (hardware) disk usage. \n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType) * 100 / (sum(ray_node_disk_free{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType) + sum(ray_node_disk_usage{instance=~\"$Instance\", RayNodeType=~\"$RayNodeType\", SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance, RayNodeType))",
     "legendFormat": "Disk Used: {{instance}} ({{RayNodeType}})"
    }
   ]
  },
  { "title": "Ray Tasks & Actors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "All Tasks by State",
   "type": "timeseries",
   "description": "Current count of tasks, grouped by scheduler state (e.g., pending, running, finished).\n\nState: the task state, as described by rpc::TaskStatus proto in common.proto. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry=\"0\",State=~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (State), 0)",
     "legendFormat": "{{State}}"
    },
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry!=\"0\",State=~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (State), 0)",
     "legendFormat": "{{State}} (retry)"
    }
   ]
  },
  {
   "title": "Active Tasks by Name",
   "type": "timeseries",
   "description": "Current count of active tasks (i.e. pending or running; not finished), grouped by task name. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (Name), 0)",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "clamp_min(sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (Name), 0)",
     "legendFormat": "{{Name}} (retry)"
    }
   ]
  },
  {
   "title": "All Actors by State",
   "type": "timeseries",
   "description": "Note: not impacted by \"Instance\" variable.\n\nCurrent count of actors, grouped by lifecycle state (e.g., alive, restarting, dead/terminated).\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "targets": [
    {
     "expr": "sum(ray_actors{Source=\"gcs\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Alive Actors by Name",
   "type": "timeseries",
   "description": "Current count of alive actors, grouped by actor name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "actors" } },
   "targets": [
    {
     "expr": "sum(ray_actors{State!=\"DEAD\",Source=\"executor\",NodeAddress=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  { "title": "Ray Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Logical CPUs Usage",
   "type": "timeseries",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors. PENDING means the number of CPUs that will be available when new nodes are up after the autoscaler scales up.\n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"CPU\",State=\"USED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance)",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Logical GPUs Usage",
   "type": "timeseries",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. PENDING means the number of GPUs that will be available when new nodes are up after the autoscaler scales up.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"GPU\",State=\"USED\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance)",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Object Store Memory Usage",
   "type": "timeseries",
   "description": "Object store memory usage by instance, including memory that has been spilled to disk. The dotted line indicates the object store memory capacity. This metric can go over the max capacity in case of spillage to disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Object Store Memory Usage %",
   "type": "timeseries",
   "description": "Object store memory usage % by instance, including memory that has been spilled to disk. This metric can go over 100% in case of spillage to disk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance) * 100 / sum(ray_resources{Name=\"object_store_memory\",instance=~\"$Instance\",SessionName=~\"$SessionName\",sagemaker_training_job_name=~\"$TrainingJobName\",instance_type=~\"$InstanceType\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "100", "legendFormat": "MAX" }
   ]
  }
 ]
}